# Generated by Django 3.2.13 on 2022-06-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
