# Generated by Django 3.2 on 2023-06-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20230628_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tag',
            new_name='tags',
        ),
    ]
