# Generated by Django 3.2.13 on 2022-06-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notebook'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notes', to='notes.note'),
        ),
    ]
