# Generated by Django 3.2 on 2023-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20230628_0932'),
        ('books', '0004_auto_20220721_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='notebook',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='booktags', to='notes.Tag'),
        ),
    ]
