# Generated by Django 3.2 on 2023-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20230628_0932'),
        ('books', '0005_auto_20230628_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_tags', to='notes.Tag'),
        ),
    ]
