# Generated by Django 3.2 on 2023-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20230628_0932'),
        ('todos', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='todo_tags', to='notes.Tag'),
        ),
    ]
